package(default_visibility = ["//visibility:public"])

cc_library(
    name = "distfs-network",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.h"]),
    deps = [
        "//common:distfs-common",
        "//data:distfs-data",
    ],
)
