package(default_visibility = ["//visibility:public"])

cc_library(
    name = "distfs-common",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.h"]),
    deps = [
        "//external:libssl",
    ]
)
